/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as HomeLayoutImport } from './routes/_homeLayout'
import { Route as HomeLayoutIndexImport } from './routes/_homeLayout/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AdminAdminLayoutImport } from './routes/admin/_adminLayout'
import { Route as HomeLayoutStudyProgramProfileImport } from './routes/_homeLayout/studyProgramProfile'
import { Route as HomeLayoutStudentsAssociationInfoImport } from './routes/_homeLayout/studentsAssociationInfo'
import { Route as AdminAdminLayoutIndexImport } from './routes/admin/_adminLayout/index'
import { Route as HomeLayoutVacancyIndexImport } from './routes/_homeLayout/vacancy/index'
import { Route as HomeLayoutAnnouncementIndexImport } from './routes/_homeLayout/announcement/index'
import { Route as HomeLayoutAlumniInfoIndexImport } from './routes/_homeLayout/alumni-info/index'
import { Route as AdminAdminLayoutVacancyImport } from './routes/admin/_adminLayout/vacancy'
import { Route as AdminAdminLayoutAnnouncementImport } from './routes/admin/_adminLayout/announcement'
import { Route as AdminAdminLayoutVacancyIndexImport } from './routes/admin/_adminLayout/vacancy/index'
import { Route as AdminAdminLayoutAnnouncementIndexImport } from './routes/admin/_adminLayout/announcement/index'
import { Route as AdminAdminLayoutAlumniInfoIndexImport } from './routes/admin/_adminLayout/alumni-info/index'
import { Route as HomeLayoutAnnouncementAnnouncementIdIndexImport } from './routes/_homeLayout/announcement/$announcementId/index'
import { Route as AdminAdminLayoutVacancyAddImport } from './routes/admin/_adminLayout/vacancy/add'
import { Route as AdminAdminLayoutAnnouncementAddImport } from './routes/admin/_adminLayout/announcement/add'
import { Route as AdminAdminLayoutAlumniInfoAddImport } from './routes/admin/_adminLayout/alumni-info/add'
import { Route as AdminAdminLayoutVacancyVacancyIdIndexImport } from './routes/admin/_adminLayout/vacancy/$vacancyId/index'
import { Route as AdminAdminLayoutAnnouncementAnnouncementIdIndexImport } from './routes/admin/_adminLayout/announcement/$announcementId/index'
import { Route as AdminAdminLayoutAlumniInfoAlumniIdIndexImport } from './routes/admin/_adminLayout/alumni-info/$alumniId/index'
import { Route as AdminAdminLayoutVacancyVacancyIdEditImport } from './routes/admin/_adminLayout/vacancy/$vacancyId/edit'
import { Route as AdminAdminLayoutAnnouncementAnnouncementIdEditImport } from './routes/admin/_adminLayout/announcement/$announcementId/edit'
import { Route as AdminAdminLayoutAlumniInfoAlumniIdEditImport } from './routes/admin/_adminLayout/alumni-info/$alumniId/edit'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_homeLayout',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutIndexRoute = HomeLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminAdminLayoutRoute = AdminAdminLayoutImport.update({
  id: '/_adminLayout',
  getParentRoute: () => AdminRoute,
} as any)

const HomeLayoutStudyProgramProfileRoute =
  HomeLayoutStudyProgramProfileImport.update({
    id: '/studyProgramProfile',
    path: '/studyProgramProfile',
    getParentRoute: () => HomeLayoutRoute,
  } as any)

const HomeLayoutStudentsAssociationInfoRoute =
  HomeLayoutStudentsAssociationInfoImport.update({
    id: '/studentsAssociationInfo',
    path: '/studentsAssociationInfo',
    getParentRoute: () => HomeLayoutRoute,
  } as any)

const AdminAdminLayoutIndexRoute = AdminAdminLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminLayoutRoute,
} as any)

const HomeLayoutVacancyIndexRoute = HomeLayoutVacancyIndexImport.update({
  id: '/vacancy/',
  path: '/vacancy/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutAnnouncementIndexRoute =
  HomeLayoutAnnouncementIndexImport.update({
    id: '/announcement/',
    path: '/announcement/',
    getParentRoute: () => HomeLayoutRoute,
  } as any)

const HomeLayoutAlumniInfoIndexRoute = HomeLayoutAlumniInfoIndexImport.update({
  id: '/alumni-info/',
  path: '/alumni-info/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const AdminAdminLayoutVacancyRoute = AdminAdminLayoutVacancyImport.update({
  id: '/vacancy',
  path: '/vacancy',
  getParentRoute: () => AdminAdminLayoutRoute,
} as any)

const AdminAdminLayoutAnnouncementRoute =
  AdminAdminLayoutAnnouncementImport.update({
    id: '/announcement',
    path: '/announcement',
    getParentRoute: () => AdminAdminLayoutRoute,
  } as any)

const AdminAdminLayoutVacancyIndexRoute =
  AdminAdminLayoutVacancyIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminLayoutVacancyRoute,
  } as any)

const AdminAdminLayoutAnnouncementIndexRoute =
  AdminAdminLayoutAnnouncementIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminLayoutAnnouncementRoute,
  } as any)

const AdminAdminLayoutAlumniInfoIndexRoute =
  AdminAdminLayoutAlumniInfoIndexImport.update({
    id: '/alumni-info/',
    path: '/alumni-info/',
    getParentRoute: () => AdminAdminLayoutRoute,
  } as any)

const HomeLayoutAnnouncementAnnouncementIdIndexRoute =
  HomeLayoutAnnouncementAnnouncementIdIndexImport.update({
    id: '/announcement/$announcementId/',
    path: '/announcement/$announcementId/',
    getParentRoute: () => HomeLayoutRoute,
  } as any)

const AdminAdminLayoutVacancyAddRoute = AdminAdminLayoutVacancyAddImport.update(
  {
    id: '/add',
    path: '/add',
    getParentRoute: () => AdminAdminLayoutVacancyRoute,
  } as any,
)

const AdminAdminLayoutAnnouncementAddRoute =
  AdminAdminLayoutAnnouncementAddImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AdminAdminLayoutAnnouncementRoute,
  } as any)

const AdminAdminLayoutAlumniInfoAddRoute =
  AdminAdminLayoutAlumniInfoAddImport.update({
    id: '/alumni-info/add',
    path: '/alumni-info/add',
    getParentRoute: () => AdminAdminLayoutRoute,
  } as any)

const AdminAdminLayoutVacancyVacancyIdIndexRoute =
  AdminAdminLayoutVacancyVacancyIdIndexImport.update({
    id: '/$vacancyId/',
    path: '/$vacancyId/',
    getParentRoute: () => AdminAdminLayoutVacancyRoute,
  } as any)

const AdminAdminLayoutAnnouncementAnnouncementIdIndexRoute =
  AdminAdminLayoutAnnouncementAnnouncementIdIndexImport.update({
    id: '/$announcementId/',
    path: '/$announcementId/',
    getParentRoute: () => AdminAdminLayoutAnnouncementRoute,
  } as any)

const AdminAdminLayoutAlumniInfoAlumniIdIndexRoute =
  AdminAdminLayoutAlumniInfoAlumniIdIndexImport.update({
    id: '/alumni-info/$alumniId/',
    path: '/alumni-info/$alumniId/',
    getParentRoute: () => AdminAdminLayoutRoute,
  } as any)

const AdminAdminLayoutVacancyVacancyIdEditRoute =
  AdminAdminLayoutVacancyVacancyIdEditImport.update({
    id: '/$vacancyId/edit',
    path: '/$vacancyId/edit',
    getParentRoute: () => AdminAdminLayoutVacancyRoute,
  } as any)

const AdminAdminLayoutAnnouncementAnnouncementIdEditRoute =
  AdminAdminLayoutAnnouncementAnnouncementIdEditImport.update({
    id: '/$announcementId/edit',
    path: '/$announcementId/edit',
    getParentRoute: () => AdminAdminLayoutAnnouncementRoute,
  } as any)

const AdminAdminLayoutAlumniInfoAlumniIdEditRoute =
  AdminAdminLayoutAlumniInfoAlumniIdEditImport.update({
    id: '/alumni-info/$alumniId/edit',
    path: '/alumni-info/$alumniId/edit',
    getParentRoute: () => AdminAdminLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_homeLayout': {
      id: '/_homeLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_homeLayout/studentsAssociationInfo': {
      id: '/_homeLayout/studentsAssociationInfo'
      path: '/studentsAssociationInfo'
      fullPath: '/studentsAssociationInfo'
      preLoaderRoute: typeof HomeLayoutStudentsAssociationInfoImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/studyProgramProfile': {
      id: '/_homeLayout/studyProgramProfile'
      path: '/studyProgramProfile'
      fullPath: '/studyProgramProfile'
      preLoaderRoute: typeof HomeLayoutStudyProgramProfileImport
      parentRoute: typeof HomeLayoutImport
    }
    '/admin/_adminLayout': {
      id: '/admin/_adminLayout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminLayoutImport
      parentRoute: typeof AdminImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/_homeLayout/': {
      id: '/_homeLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/admin/_adminLayout/announcement': {
      id: '/admin/_adminLayout/announcement'
      path: '/announcement'
      fullPath: '/admin/announcement'
      preLoaderRoute: typeof AdminAdminLayoutAnnouncementImport
      parentRoute: typeof AdminAdminLayoutImport
    }
    '/admin/_adminLayout/vacancy': {
      id: '/admin/_adminLayout/vacancy'
      path: '/vacancy'
      fullPath: '/admin/vacancy'
      preLoaderRoute: typeof AdminAdminLayoutVacancyImport
      parentRoute: typeof AdminAdminLayoutImport
    }
    '/_homeLayout/alumni-info/': {
      id: '/_homeLayout/alumni-info/'
      path: '/alumni-info'
      fullPath: '/alumni-info'
      preLoaderRoute: typeof HomeLayoutAlumniInfoIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/announcement/': {
      id: '/_homeLayout/announcement/'
      path: '/announcement'
      fullPath: '/announcement'
      preLoaderRoute: typeof HomeLayoutAnnouncementIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/vacancy/': {
      id: '/_homeLayout/vacancy/'
      path: '/vacancy'
      fullPath: '/vacancy'
      preLoaderRoute: typeof HomeLayoutVacancyIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/admin/_adminLayout/': {
      id: '/admin/_adminLayout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminLayoutIndexImport
      parentRoute: typeof AdminAdminLayoutImport
    }
    '/admin/_adminLayout/alumni-info/add': {
      id: '/admin/_adminLayout/alumni-info/add'
      path: '/alumni-info/add'
      fullPath: '/admin/alumni-info/add'
      preLoaderRoute: typeof AdminAdminLayoutAlumniInfoAddImport
      parentRoute: typeof AdminAdminLayoutImport
    }
    '/admin/_adminLayout/announcement/add': {
      id: '/admin/_adminLayout/announcement/add'
      path: '/add'
      fullPath: '/admin/announcement/add'
      preLoaderRoute: typeof AdminAdminLayoutAnnouncementAddImport
      parentRoute: typeof AdminAdminLayoutAnnouncementImport
    }
    '/admin/_adminLayout/vacancy/add': {
      id: '/admin/_adminLayout/vacancy/add'
      path: '/add'
      fullPath: '/admin/vacancy/add'
      preLoaderRoute: typeof AdminAdminLayoutVacancyAddImport
      parentRoute: typeof AdminAdminLayoutVacancyImport
    }
    '/_homeLayout/announcement/$announcementId/': {
      id: '/_homeLayout/announcement/$announcementId/'
      path: '/announcement/$announcementId'
      fullPath: '/announcement/$announcementId'
      preLoaderRoute: typeof HomeLayoutAnnouncementAnnouncementIdIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/admin/_adminLayout/alumni-info/': {
      id: '/admin/_adminLayout/alumni-info/'
      path: '/alumni-info'
      fullPath: '/admin/alumni-info'
      preLoaderRoute: typeof AdminAdminLayoutAlumniInfoIndexImport
      parentRoute: typeof AdminAdminLayoutImport
    }
    '/admin/_adminLayout/announcement/': {
      id: '/admin/_adminLayout/announcement/'
      path: '/'
      fullPath: '/admin/announcement/'
      preLoaderRoute: typeof AdminAdminLayoutAnnouncementIndexImport
      parentRoute: typeof AdminAdminLayoutAnnouncementImport
    }
    '/admin/_adminLayout/vacancy/': {
      id: '/admin/_adminLayout/vacancy/'
      path: '/'
      fullPath: '/admin/vacancy/'
      preLoaderRoute: typeof AdminAdminLayoutVacancyIndexImport
      parentRoute: typeof AdminAdminLayoutVacancyImport
    }
    '/admin/_adminLayout/alumni-info/$alumniId/edit': {
      id: '/admin/_adminLayout/alumni-info/$alumniId/edit'
      path: '/alumni-info/$alumniId/edit'
      fullPath: '/admin/alumni-info/$alumniId/edit'
      preLoaderRoute: typeof AdminAdminLayoutAlumniInfoAlumniIdEditImport
      parentRoute: typeof AdminAdminLayoutImport
    }
    '/admin/_adminLayout/announcement/$announcementId/edit': {
      id: '/admin/_adminLayout/announcement/$announcementId/edit'
      path: '/$announcementId/edit'
      fullPath: '/admin/announcement/$announcementId/edit'
      preLoaderRoute: typeof AdminAdminLayoutAnnouncementAnnouncementIdEditImport
      parentRoute: typeof AdminAdminLayoutAnnouncementImport
    }
    '/admin/_adminLayout/vacancy/$vacancyId/edit': {
      id: '/admin/_adminLayout/vacancy/$vacancyId/edit'
      path: '/$vacancyId/edit'
      fullPath: '/admin/vacancy/$vacancyId/edit'
      preLoaderRoute: typeof AdminAdminLayoutVacancyVacancyIdEditImport
      parentRoute: typeof AdminAdminLayoutVacancyImport
    }
    '/admin/_adminLayout/alumni-info/$alumniId/': {
      id: '/admin/_adminLayout/alumni-info/$alumniId/'
      path: '/alumni-info/$alumniId'
      fullPath: '/admin/alumni-info/$alumniId'
      preLoaderRoute: typeof AdminAdminLayoutAlumniInfoAlumniIdIndexImport
      parentRoute: typeof AdminAdminLayoutImport
    }
    '/admin/_adminLayout/announcement/$announcementId/': {
      id: '/admin/_adminLayout/announcement/$announcementId/'
      path: '/$announcementId'
      fullPath: '/admin/announcement/$announcementId'
      preLoaderRoute: typeof AdminAdminLayoutAnnouncementAnnouncementIdIndexImport
      parentRoute: typeof AdminAdminLayoutAnnouncementImport
    }
    '/admin/_adminLayout/vacancy/$vacancyId/': {
      id: '/admin/_adminLayout/vacancy/$vacancyId/'
      path: '/$vacancyId'
      fullPath: '/admin/vacancy/$vacancyId'
      preLoaderRoute: typeof AdminAdminLayoutVacancyVacancyIdIndexImport
      parentRoute: typeof AdminAdminLayoutVacancyImport
    }
  }
}

// Create and export the route tree

interface HomeLayoutRouteChildren {
  HomeLayoutStudentsAssociationInfoRoute: typeof HomeLayoutStudentsAssociationInfoRoute
  HomeLayoutStudyProgramProfileRoute: typeof HomeLayoutStudyProgramProfileRoute
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
  HomeLayoutAlumniInfoIndexRoute: typeof HomeLayoutAlumniInfoIndexRoute
  HomeLayoutAnnouncementIndexRoute: typeof HomeLayoutAnnouncementIndexRoute
  HomeLayoutVacancyIndexRoute: typeof HomeLayoutVacancyIndexRoute
  HomeLayoutAnnouncementAnnouncementIdIndexRoute: typeof HomeLayoutAnnouncementAnnouncementIdIndexRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutStudentsAssociationInfoRoute:
    HomeLayoutStudentsAssociationInfoRoute,
  HomeLayoutStudyProgramProfileRoute: HomeLayoutStudyProgramProfileRoute,
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
  HomeLayoutAlumniInfoIndexRoute: HomeLayoutAlumniInfoIndexRoute,
  HomeLayoutAnnouncementIndexRoute: HomeLayoutAnnouncementIndexRoute,
  HomeLayoutVacancyIndexRoute: HomeLayoutVacancyIndexRoute,
  HomeLayoutAnnouncementAnnouncementIdIndexRoute:
    HomeLayoutAnnouncementAnnouncementIdIndexRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

interface AdminAdminLayoutAnnouncementRouteChildren {
  AdminAdminLayoutAnnouncementAddRoute: typeof AdminAdminLayoutAnnouncementAddRoute
  AdminAdminLayoutAnnouncementIndexRoute: typeof AdminAdminLayoutAnnouncementIndexRoute
  AdminAdminLayoutAnnouncementAnnouncementIdEditRoute: typeof AdminAdminLayoutAnnouncementAnnouncementIdEditRoute
  AdminAdminLayoutAnnouncementAnnouncementIdIndexRoute: typeof AdminAdminLayoutAnnouncementAnnouncementIdIndexRoute
}

const AdminAdminLayoutAnnouncementRouteChildren: AdminAdminLayoutAnnouncementRouteChildren =
  {
    AdminAdminLayoutAnnouncementAddRoute: AdminAdminLayoutAnnouncementAddRoute,
    AdminAdminLayoutAnnouncementIndexRoute:
      AdminAdminLayoutAnnouncementIndexRoute,
    AdminAdminLayoutAnnouncementAnnouncementIdEditRoute:
      AdminAdminLayoutAnnouncementAnnouncementIdEditRoute,
    AdminAdminLayoutAnnouncementAnnouncementIdIndexRoute:
      AdminAdminLayoutAnnouncementAnnouncementIdIndexRoute,
  }

const AdminAdminLayoutAnnouncementRouteWithChildren =
  AdminAdminLayoutAnnouncementRoute._addFileChildren(
    AdminAdminLayoutAnnouncementRouteChildren,
  )

interface AdminAdminLayoutVacancyRouteChildren {
  AdminAdminLayoutVacancyAddRoute: typeof AdminAdminLayoutVacancyAddRoute
  AdminAdminLayoutVacancyIndexRoute: typeof AdminAdminLayoutVacancyIndexRoute
  AdminAdminLayoutVacancyVacancyIdEditRoute: typeof AdminAdminLayoutVacancyVacancyIdEditRoute
  AdminAdminLayoutVacancyVacancyIdIndexRoute: typeof AdminAdminLayoutVacancyVacancyIdIndexRoute
}

const AdminAdminLayoutVacancyRouteChildren: AdminAdminLayoutVacancyRouteChildren =
  {
    AdminAdminLayoutVacancyAddRoute: AdminAdminLayoutVacancyAddRoute,
    AdminAdminLayoutVacancyIndexRoute: AdminAdminLayoutVacancyIndexRoute,
    AdminAdminLayoutVacancyVacancyIdEditRoute:
      AdminAdminLayoutVacancyVacancyIdEditRoute,
    AdminAdminLayoutVacancyVacancyIdIndexRoute:
      AdminAdminLayoutVacancyVacancyIdIndexRoute,
  }

const AdminAdminLayoutVacancyRouteWithChildren =
  AdminAdminLayoutVacancyRoute._addFileChildren(
    AdminAdminLayoutVacancyRouteChildren,
  )

interface AdminAdminLayoutRouteChildren {
  AdminAdminLayoutAnnouncementRoute: typeof AdminAdminLayoutAnnouncementRouteWithChildren
  AdminAdminLayoutVacancyRoute: typeof AdminAdminLayoutVacancyRouteWithChildren
  AdminAdminLayoutIndexRoute: typeof AdminAdminLayoutIndexRoute
  AdminAdminLayoutAlumniInfoAddRoute: typeof AdminAdminLayoutAlumniInfoAddRoute
  AdminAdminLayoutAlumniInfoIndexRoute: typeof AdminAdminLayoutAlumniInfoIndexRoute
  AdminAdminLayoutAlumniInfoAlumniIdEditRoute: typeof AdminAdminLayoutAlumniInfoAlumniIdEditRoute
  AdminAdminLayoutAlumniInfoAlumniIdIndexRoute: typeof AdminAdminLayoutAlumniInfoAlumniIdIndexRoute
}

const AdminAdminLayoutRouteChildren: AdminAdminLayoutRouteChildren = {
  AdminAdminLayoutAnnouncementRoute:
    AdminAdminLayoutAnnouncementRouteWithChildren,
  AdminAdminLayoutVacancyRoute: AdminAdminLayoutVacancyRouteWithChildren,
  AdminAdminLayoutIndexRoute: AdminAdminLayoutIndexRoute,
  AdminAdminLayoutAlumniInfoAddRoute: AdminAdminLayoutAlumniInfoAddRoute,
  AdminAdminLayoutAlumniInfoIndexRoute: AdminAdminLayoutAlumniInfoIndexRoute,
  AdminAdminLayoutAlumniInfoAlumniIdEditRoute:
    AdminAdminLayoutAlumniInfoAlumniIdEditRoute,
  AdminAdminLayoutAlumniInfoAlumniIdIndexRoute:
    AdminAdminLayoutAlumniInfoAlumniIdIndexRoute,
}

const AdminAdminLayoutRouteWithChildren =
  AdminAdminLayoutRoute._addFileChildren(AdminAdminLayoutRouteChildren)

interface AdminRouteChildren {
  AdminAdminLayoutRoute: typeof AdminAdminLayoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminLayoutRoute: AdminAdminLayoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof HomeLayoutRouteWithChildren
  '/admin': typeof AdminAdminLayoutRouteWithChildren
  '/studentsAssociationInfo': typeof HomeLayoutStudentsAssociationInfoRoute
  '/studyProgramProfile': typeof HomeLayoutStudyProgramProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof HomeLayoutIndexRoute
  '/admin/announcement': typeof AdminAdminLayoutAnnouncementRouteWithChildren
  '/admin/vacancy': typeof AdminAdminLayoutVacancyRouteWithChildren
  '/alumni-info': typeof HomeLayoutAlumniInfoIndexRoute
  '/announcement': typeof HomeLayoutAnnouncementIndexRoute
  '/vacancy': typeof HomeLayoutVacancyIndexRoute
  '/admin/': typeof AdminAdminLayoutIndexRoute
  '/admin/alumni-info/add': typeof AdminAdminLayoutAlumniInfoAddRoute
  '/admin/announcement/add': typeof AdminAdminLayoutAnnouncementAddRoute
  '/admin/vacancy/add': typeof AdminAdminLayoutVacancyAddRoute
  '/announcement/$announcementId': typeof HomeLayoutAnnouncementAnnouncementIdIndexRoute
  '/admin/alumni-info': typeof AdminAdminLayoutAlumniInfoIndexRoute
  '/admin/announcement/': typeof AdminAdminLayoutAnnouncementIndexRoute
  '/admin/vacancy/': typeof AdminAdminLayoutVacancyIndexRoute
  '/admin/alumni-info/$alumniId/edit': typeof AdminAdminLayoutAlumniInfoAlumniIdEditRoute
  '/admin/announcement/$announcementId/edit': typeof AdminAdminLayoutAnnouncementAnnouncementIdEditRoute
  '/admin/vacancy/$vacancyId/edit': typeof AdminAdminLayoutVacancyVacancyIdEditRoute
  '/admin/alumni-info/$alumniId': typeof AdminAdminLayoutAlumniInfoAlumniIdIndexRoute
  '/admin/announcement/$announcementId': typeof AdminAdminLayoutAnnouncementAnnouncementIdIndexRoute
  '/admin/vacancy/$vacancyId': typeof AdminAdminLayoutVacancyVacancyIdIndexRoute
}

export interface FileRoutesByTo {
  '/admin': typeof AdminAdminLayoutIndexRoute
  '/studentsAssociationInfo': typeof HomeLayoutStudentsAssociationInfoRoute
  '/studyProgramProfile': typeof HomeLayoutStudyProgramProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof HomeLayoutIndexRoute
  '/alumni-info': typeof HomeLayoutAlumniInfoIndexRoute
  '/announcement': typeof HomeLayoutAnnouncementIndexRoute
  '/vacancy': typeof HomeLayoutVacancyIndexRoute
  '/admin/alumni-info/add': typeof AdminAdminLayoutAlumniInfoAddRoute
  '/admin/announcement/add': typeof AdminAdminLayoutAnnouncementAddRoute
  '/admin/vacancy/add': typeof AdminAdminLayoutVacancyAddRoute
  '/announcement/$announcementId': typeof HomeLayoutAnnouncementAnnouncementIdIndexRoute
  '/admin/alumni-info': typeof AdminAdminLayoutAlumniInfoIndexRoute
  '/admin/announcement': typeof AdminAdminLayoutAnnouncementIndexRoute
  '/admin/vacancy': typeof AdminAdminLayoutVacancyIndexRoute
  '/admin/alumni-info/$alumniId/edit': typeof AdminAdminLayoutAlumniInfoAlumniIdEditRoute
  '/admin/announcement/$announcementId/edit': typeof AdminAdminLayoutAnnouncementAnnouncementIdEditRoute
  '/admin/vacancy/$vacancyId/edit': typeof AdminAdminLayoutVacancyVacancyIdEditRoute
  '/admin/alumni-info/$alumniId': typeof AdminAdminLayoutAlumniInfoAlumniIdIndexRoute
  '/admin/announcement/$announcementId': typeof AdminAdminLayoutAnnouncementAnnouncementIdIndexRoute
  '/admin/vacancy/$vacancyId': typeof AdminAdminLayoutVacancyVacancyIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_homeLayout': typeof HomeLayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_homeLayout/studentsAssociationInfo': typeof HomeLayoutStudentsAssociationInfoRoute
  '/_homeLayout/studyProgramProfile': typeof HomeLayoutStudyProgramProfileRoute
  '/admin/_adminLayout': typeof AdminAdminLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_homeLayout/': typeof HomeLayoutIndexRoute
  '/admin/_adminLayout/announcement': typeof AdminAdminLayoutAnnouncementRouteWithChildren
  '/admin/_adminLayout/vacancy': typeof AdminAdminLayoutVacancyRouteWithChildren
  '/_homeLayout/alumni-info/': typeof HomeLayoutAlumniInfoIndexRoute
  '/_homeLayout/announcement/': typeof HomeLayoutAnnouncementIndexRoute
  '/_homeLayout/vacancy/': typeof HomeLayoutVacancyIndexRoute
  '/admin/_adminLayout/': typeof AdminAdminLayoutIndexRoute
  '/admin/_adminLayout/alumni-info/add': typeof AdminAdminLayoutAlumniInfoAddRoute
  '/admin/_adminLayout/announcement/add': typeof AdminAdminLayoutAnnouncementAddRoute
  '/admin/_adminLayout/vacancy/add': typeof AdminAdminLayoutVacancyAddRoute
  '/_homeLayout/announcement/$announcementId/': typeof HomeLayoutAnnouncementAnnouncementIdIndexRoute
  '/admin/_adminLayout/alumni-info/': typeof AdminAdminLayoutAlumniInfoIndexRoute
  '/admin/_adminLayout/announcement/': typeof AdminAdminLayoutAnnouncementIndexRoute
  '/admin/_adminLayout/vacancy/': typeof AdminAdminLayoutVacancyIndexRoute
  '/admin/_adminLayout/alumni-info/$alumniId/edit': typeof AdminAdminLayoutAlumniInfoAlumniIdEditRoute
  '/admin/_adminLayout/announcement/$announcementId/edit': typeof AdminAdminLayoutAnnouncementAnnouncementIdEditRoute
  '/admin/_adminLayout/vacancy/$vacancyId/edit': typeof AdminAdminLayoutVacancyVacancyIdEditRoute
  '/admin/_adminLayout/alumni-info/$alumniId/': typeof AdminAdminLayoutAlumniInfoAlumniIdIndexRoute
  '/admin/_adminLayout/announcement/$announcementId/': typeof AdminAdminLayoutAnnouncementAnnouncementIdIndexRoute
  '/admin/_adminLayout/vacancy/$vacancyId/': typeof AdminAdminLayoutVacancyVacancyIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/studentsAssociationInfo'
    | '/studyProgramProfile'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/admin/announcement'
    | '/admin/vacancy'
    | '/alumni-info'
    | '/announcement'
    | '/vacancy'
    | '/admin/'
    | '/admin/alumni-info/add'
    | '/admin/announcement/add'
    | '/admin/vacancy/add'
    | '/announcement/$announcementId'
    | '/admin/alumni-info'
    | '/admin/announcement/'
    | '/admin/vacancy/'
    | '/admin/alumni-info/$alumniId/edit'
    | '/admin/announcement/$announcementId/edit'
    | '/admin/vacancy/$vacancyId/edit'
    | '/admin/alumni-info/$alumniId'
    | '/admin/announcement/$announcementId'
    | '/admin/vacancy/$vacancyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/studentsAssociationInfo'
    | '/studyProgramProfile'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/alumni-info'
    | '/announcement'
    | '/vacancy'
    | '/admin/alumni-info/add'
    | '/admin/announcement/add'
    | '/admin/vacancy/add'
    | '/announcement/$announcementId'
    | '/admin/alumni-info'
    | '/admin/announcement'
    | '/admin/vacancy'
    | '/admin/alumni-info/$alumniId/edit'
    | '/admin/announcement/$announcementId/edit'
    | '/admin/vacancy/$vacancyId/edit'
    | '/admin/alumni-info/$alumniId'
    | '/admin/announcement/$announcementId'
    | '/admin/vacancy/$vacancyId'
  id:
    | '__root__'
    | '/_homeLayout'
    | '/admin'
    | '/_homeLayout/studentsAssociationInfo'
    | '/_homeLayout/studyProgramProfile'
    | '/admin/_adminLayout'
    | '/auth/login'
    | '/auth/register'
    | '/_homeLayout/'
    | '/admin/_adminLayout/announcement'
    | '/admin/_adminLayout/vacancy'
    | '/_homeLayout/alumni-info/'
    | '/_homeLayout/announcement/'
    | '/_homeLayout/vacancy/'
    | '/admin/_adminLayout/'
    | '/admin/_adminLayout/alumni-info/add'
    | '/admin/_adminLayout/announcement/add'
    | '/admin/_adminLayout/vacancy/add'
    | '/_homeLayout/announcement/$announcementId/'
    | '/admin/_adminLayout/alumni-info/'
    | '/admin/_adminLayout/announcement/'
    | '/admin/_adminLayout/vacancy/'
    | '/admin/_adminLayout/alumni-info/$alumniId/edit'
    | '/admin/_adminLayout/announcement/$announcementId/edit'
    | '/admin/_adminLayout/vacancy/$vacancyId/edit'
    | '/admin/_adminLayout/alumni-info/$alumniId/'
    | '/admin/_adminLayout/announcement/$announcementId/'
    | '/admin/_adminLayout/vacancy/$vacancyId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_homeLayout",
        "/admin",
        "/auth/login",
        "/auth/register"
      ]
    },
    "/_homeLayout": {
      "filePath": "_homeLayout.tsx",
      "children": [
        "/_homeLayout/studentsAssociationInfo",
        "/_homeLayout/studyProgramProfile",
        "/_homeLayout/",
        "/_homeLayout/alumni-info/",
        "/_homeLayout/announcement/",
        "/_homeLayout/vacancy/",
        "/_homeLayout/announcement/$announcementId/"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/_adminLayout"
      ]
    },
    "/_homeLayout/studentsAssociationInfo": {
      "filePath": "_homeLayout/studentsAssociationInfo.tsx",
      "parent": "/_homeLayout"
    },
    "/_homeLayout/studyProgramProfile": {
      "filePath": "_homeLayout/studyProgramProfile.tsx",
      "parent": "/_homeLayout"
    },
    "/admin/_adminLayout": {
      "filePath": "admin/_adminLayout.tsx",
      "parent": "/admin",
      "children": [
        "/admin/_adminLayout/announcement",
        "/admin/_adminLayout/vacancy",
        "/admin/_adminLayout/",
        "/admin/_adminLayout/alumni-info/add",
        "/admin/_adminLayout/alumni-info/",
        "/admin/_adminLayout/alumni-info/$alumniId/edit",
        "/admin/_adminLayout/alumni-info/$alumniId/"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/_homeLayout/": {
      "filePath": "_homeLayout/index.tsx",
      "parent": "/_homeLayout"
    },
    "/admin/_adminLayout/announcement": {
      "filePath": "admin/_adminLayout/announcement.tsx",
      "parent": "/admin/_adminLayout",
      "children": [
        "/admin/_adminLayout/announcement/add",
        "/admin/_adminLayout/announcement/",
        "/admin/_adminLayout/announcement/$announcementId/edit",
        "/admin/_adminLayout/announcement/$announcementId/"
      ]
    },
    "/admin/_adminLayout/vacancy": {
      "filePath": "admin/_adminLayout/vacancy.tsx",
      "parent": "/admin/_adminLayout",
      "children": [
        "/admin/_adminLayout/vacancy/add",
        "/admin/_adminLayout/vacancy/",
        "/admin/_adminLayout/vacancy/$vacancyId/edit",
        "/admin/_adminLayout/vacancy/$vacancyId/"
      ]
    },
    "/_homeLayout/alumni-info/": {
      "filePath": "_homeLayout/alumni-info/index.tsx",
      "parent": "/_homeLayout"
    },
    "/_homeLayout/announcement/": {
      "filePath": "_homeLayout/announcement/index.tsx",
      "parent": "/_homeLayout"
    },
    "/_homeLayout/vacancy/": {
      "filePath": "_homeLayout/vacancy/index.tsx",
      "parent": "/_homeLayout"
    },
    "/admin/_adminLayout/": {
      "filePath": "admin/_adminLayout/index.tsx",
      "parent": "/admin/_adminLayout"
    },
    "/admin/_adminLayout/alumni-info/add": {
      "filePath": "admin/_adminLayout/alumni-info/add.tsx",
      "parent": "/admin/_adminLayout"
    },
    "/admin/_adminLayout/announcement/add": {
      "filePath": "admin/_adminLayout/announcement/add.tsx",
      "parent": "/admin/_adminLayout/announcement"
    },
    "/admin/_adminLayout/vacancy/add": {
      "filePath": "admin/_adminLayout/vacancy/add.tsx",
      "parent": "/admin/_adminLayout/vacancy"
    },
    "/_homeLayout/announcement/$announcementId/": {
      "filePath": "_homeLayout/announcement/$announcementId/index.tsx",
      "parent": "/_homeLayout"
    },
    "/admin/_adminLayout/alumni-info/": {
      "filePath": "admin/_adminLayout/alumni-info/index.tsx",
      "parent": "/admin/_adminLayout"
    },
    "/admin/_adminLayout/announcement/": {
      "filePath": "admin/_adminLayout/announcement/index.tsx",
      "parent": "/admin/_adminLayout/announcement"
    },
    "/admin/_adminLayout/vacancy/": {
      "filePath": "admin/_adminLayout/vacancy/index.tsx",
      "parent": "/admin/_adminLayout/vacancy"
    },
    "/admin/_adminLayout/alumni-info/$alumniId/edit": {
      "filePath": "admin/_adminLayout/alumni-info/$alumniId/edit.tsx",
      "parent": "/admin/_adminLayout"
    },
    "/admin/_adminLayout/announcement/$announcementId/edit": {
      "filePath": "admin/_adminLayout/announcement/$announcementId/edit.tsx",
      "parent": "/admin/_adminLayout/announcement"
    },
    "/admin/_adminLayout/vacancy/$vacancyId/edit": {
      "filePath": "admin/_adminLayout/vacancy/$vacancyId/edit.tsx",
      "parent": "/admin/_adminLayout/vacancy"
    },
    "/admin/_adminLayout/alumni-info/$alumniId/": {
      "filePath": "admin/_adminLayout/alumni-info/$alumniId/index.tsx",
      "parent": "/admin/_adminLayout"
    },
    "/admin/_adminLayout/announcement/$announcementId/": {
      "filePath": "admin/_adminLayout/announcement/$announcementId/index.tsx",
      "parent": "/admin/_adminLayout/announcement"
    },
    "/admin/_adminLayout/vacancy/$vacancyId/": {
      "filePath": "admin/_adminLayout/vacancy/$vacancyId/index.tsx",
      "parent": "/admin/_adminLayout/vacancy"
    }
  }
}
ROUTE_MANIFEST_END */
