/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as HomeLayoutImport } from './routes/_homeLayout'
import { Route as HomeLayoutIndexImport } from './routes/_homeLayout/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AdminAdminLayoutImport } from './routes/admin/_adminLayout'
import { Route as HomeLayoutVacancyImport } from './routes/_homeLayout/vacancy'
import { Route as HomeLayoutStudyProgramProfileImport } from './routes/_homeLayout/studyProgramProfile'
import { Route as HomeLayoutStudentsAssociationInfoImport } from './routes/_homeLayout/studentsAssociationInfo'
import { Route as HomeLayoutAnnouncementImport } from './routes/_homeLayout/announcement'
import { Route as HomeLayoutAboutImport } from './routes/_homeLayout/about'
import { Route as AdminAdminLayoutIndexImport } from './routes/admin/_adminLayout/index'
import { Route as AdminAdminLayoutVacancyImport } from './routes/admin/_adminLayout/vacancy'
import { Route as AdminAdminLayoutAnnouncementImport } from './routes/admin/_adminLayout/announcement'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_homeLayout',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutIndexRoute = HomeLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminAdminLayoutRoute = AdminAdminLayoutImport.update({
  id: '/_adminLayout',
  getParentRoute: () => AdminRoute,
} as any)

const HomeLayoutVacancyRoute = HomeLayoutVacancyImport.update({
  id: '/vacancy',
  path: '/vacancy',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutStudyProgramProfileRoute =
  HomeLayoutStudyProgramProfileImport.update({
    id: '/studyProgramProfile',
    path: '/studyProgramProfile',
    getParentRoute: () => HomeLayoutRoute,
  } as any)

const HomeLayoutStudentsAssociationInfoRoute =
  HomeLayoutStudentsAssociationInfoImport.update({
    id: '/studentsAssociationInfo',
    path: '/studentsAssociationInfo',
    getParentRoute: () => HomeLayoutRoute,
  } as any)

const HomeLayoutAnnouncementRoute = HomeLayoutAnnouncementImport.update({
  id: '/announcement',
  path: '/announcement',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutAboutRoute = HomeLayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const AdminAdminLayoutIndexRoute = AdminAdminLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminLayoutRoute,
} as any)

const AdminAdminLayoutVacancyRoute = AdminAdminLayoutVacancyImport.update({
  id: '/vacancy',
  path: '/vacancy',
  getParentRoute: () => AdminAdminLayoutRoute,
} as any)

const AdminAdminLayoutAnnouncementRoute =
  AdminAdminLayoutAnnouncementImport.update({
    id: '/announcement',
    path: '/announcement',
    getParentRoute: () => AdminAdminLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_homeLayout': {
      id: '/_homeLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_homeLayout/about': {
      id: '/_homeLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeLayoutAboutImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/announcement': {
      id: '/_homeLayout/announcement'
      path: '/announcement'
      fullPath: '/announcement'
      preLoaderRoute: typeof HomeLayoutAnnouncementImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/studentsAssociationInfo': {
      id: '/_homeLayout/studentsAssociationInfo'
      path: '/studentsAssociationInfo'
      fullPath: '/studentsAssociationInfo'
      preLoaderRoute: typeof HomeLayoutStudentsAssociationInfoImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/studyProgramProfile': {
      id: '/_homeLayout/studyProgramProfile'
      path: '/studyProgramProfile'
      fullPath: '/studyProgramProfile'
      preLoaderRoute: typeof HomeLayoutStudyProgramProfileImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/vacancy': {
      id: '/_homeLayout/vacancy'
      path: '/vacancy'
      fullPath: '/vacancy'
      preLoaderRoute: typeof HomeLayoutVacancyImport
      parentRoute: typeof HomeLayoutImport
    }
    '/admin/_adminLayout': {
      id: '/admin/_adminLayout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminLayoutImport
      parentRoute: typeof AdminImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/_homeLayout/': {
      id: '/_homeLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/admin/_adminLayout/announcement': {
      id: '/admin/_adminLayout/announcement'
      path: '/announcement'
      fullPath: '/admin/announcement'
      preLoaderRoute: typeof AdminAdminLayoutAnnouncementImport
      parentRoute: typeof AdminAdminLayoutImport
    }
    '/admin/_adminLayout/vacancy': {
      id: '/admin/_adminLayout/vacancy'
      path: '/vacancy'
      fullPath: '/admin/vacancy'
      preLoaderRoute: typeof AdminAdminLayoutVacancyImport
      parentRoute: typeof AdminAdminLayoutImport
    }
    '/admin/_adminLayout/': {
      id: '/admin/_adminLayout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminLayoutIndexImport
      parentRoute: typeof AdminAdminLayoutImport
    }
  }
}

// Create and export the route tree

interface HomeLayoutRouteChildren {
  HomeLayoutAboutRoute: typeof HomeLayoutAboutRoute
  HomeLayoutAnnouncementRoute: typeof HomeLayoutAnnouncementRoute
  HomeLayoutStudentsAssociationInfoRoute: typeof HomeLayoutStudentsAssociationInfoRoute
  HomeLayoutStudyProgramProfileRoute: typeof HomeLayoutStudyProgramProfileRoute
  HomeLayoutVacancyRoute: typeof HomeLayoutVacancyRoute
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutAboutRoute: HomeLayoutAboutRoute,
  HomeLayoutAnnouncementRoute: HomeLayoutAnnouncementRoute,
  HomeLayoutStudentsAssociationInfoRoute:
    HomeLayoutStudentsAssociationInfoRoute,
  HomeLayoutStudyProgramProfileRoute: HomeLayoutStudyProgramProfileRoute,
  HomeLayoutVacancyRoute: HomeLayoutVacancyRoute,
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

interface AdminAdminLayoutRouteChildren {
  AdminAdminLayoutAnnouncementRoute: typeof AdminAdminLayoutAnnouncementRoute
  AdminAdminLayoutVacancyRoute: typeof AdminAdminLayoutVacancyRoute
  AdminAdminLayoutIndexRoute: typeof AdminAdminLayoutIndexRoute
}

const AdminAdminLayoutRouteChildren: AdminAdminLayoutRouteChildren = {
  AdminAdminLayoutAnnouncementRoute: AdminAdminLayoutAnnouncementRoute,
  AdminAdminLayoutVacancyRoute: AdminAdminLayoutVacancyRoute,
  AdminAdminLayoutIndexRoute: AdminAdminLayoutIndexRoute,
}

const AdminAdminLayoutRouteWithChildren =
  AdminAdminLayoutRoute._addFileChildren(AdminAdminLayoutRouteChildren)

interface AdminRouteChildren {
  AdminAdminLayoutRoute: typeof AdminAdminLayoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminLayoutRoute: AdminAdminLayoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof HomeLayoutRouteWithChildren
  '/admin': typeof AdminAdminLayoutRouteWithChildren
  '/about': typeof HomeLayoutAboutRoute
  '/announcement': typeof HomeLayoutAnnouncementRoute
  '/studentsAssociationInfo': typeof HomeLayoutStudentsAssociationInfoRoute
  '/studyProgramProfile': typeof HomeLayoutStudyProgramProfileRoute
  '/vacancy': typeof HomeLayoutVacancyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof HomeLayoutIndexRoute
  '/admin/announcement': typeof AdminAdminLayoutAnnouncementRoute
  '/admin/vacancy': typeof AdminAdminLayoutVacancyRoute
  '/admin/': typeof AdminAdminLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/admin': typeof AdminAdminLayoutIndexRoute
  '/about': typeof HomeLayoutAboutRoute
  '/announcement': typeof HomeLayoutAnnouncementRoute
  '/studentsAssociationInfo': typeof HomeLayoutStudentsAssociationInfoRoute
  '/studyProgramProfile': typeof HomeLayoutStudyProgramProfileRoute
  '/vacancy': typeof HomeLayoutVacancyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof HomeLayoutIndexRoute
  '/admin/announcement': typeof AdminAdminLayoutAnnouncementRoute
  '/admin/vacancy': typeof AdminAdminLayoutVacancyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_homeLayout': typeof HomeLayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_homeLayout/about': typeof HomeLayoutAboutRoute
  '/_homeLayout/announcement': typeof HomeLayoutAnnouncementRoute
  '/_homeLayout/studentsAssociationInfo': typeof HomeLayoutStudentsAssociationInfoRoute
  '/_homeLayout/studyProgramProfile': typeof HomeLayoutStudyProgramProfileRoute
  '/_homeLayout/vacancy': typeof HomeLayoutVacancyRoute
  '/admin/_adminLayout': typeof AdminAdminLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_homeLayout/': typeof HomeLayoutIndexRoute
  '/admin/_adminLayout/announcement': typeof AdminAdminLayoutAnnouncementRoute
  '/admin/_adminLayout/vacancy': typeof AdminAdminLayoutVacancyRoute
  '/admin/_adminLayout/': typeof AdminAdminLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/about'
    | '/announcement'
    | '/studentsAssociationInfo'
    | '/studyProgramProfile'
    | '/vacancy'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/admin/announcement'
    | '/admin/vacancy'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/about'
    | '/announcement'
    | '/studentsAssociationInfo'
    | '/studyProgramProfile'
    | '/vacancy'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/admin/announcement'
    | '/admin/vacancy'
  id:
    | '__root__'
    | '/_homeLayout'
    | '/admin'
    | '/_homeLayout/about'
    | '/_homeLayout/announcement'
    | '/_homeLayout/studentsAssociationInfo'
    | '/_homeLayout/studyProgramProfile'
    | '/_homeLayout/vacancy'
    | '/admin/_adminLayout'
    | '/auth/login'
    | '/auth/register'
    | '/_homeLayout/'
    | '/admin/_adminLayout/announcement'
    | '/admin/_adminLayout/vacancy'
    | '/admin/_adminLayout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_homeLayout",
        "/admin",
        "/auth/login",
        "/auth/register"
      ]
    },
    "/_homeLayout": {
      "filePath": "_homeLayout.tsx",
      "children": [
        "/_homeLayout/about",
        "/_homeLayout/announcement",
        "/_homeLayout/studentsAssociationInfo",
        "/_homeLayout/studyProgramProfile",
        "/_homeLayout/vacancy",
        "/_homeLayout/"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/_adminLayout"
      ]
    },
    "/_homeLayout/about": {
      "filePath": "_homeLayout/about.tsx",
      "parent": "/_homeLayout"
    },
    "/_homeLayout/announcement": {
      "filePath": "_homeLayout/announcement.tsx",
      "parent": "/_homeLayout"
    },
    "/_homeLayout/studentsAssociationInfo": {
      "filePath": "_homeLayout/studentsAssociationInfo.tsx",
      "parent": "/_homeLayout"
    },
    "/_homeLayout/studyProgramProfile": {
      "filePath": "_homeLayout/studyProgramProfile.tsx",
      "parent": "/_homeLayout"
    },
    "/_homeLayout/vacancy": {
      "filePath": "_homeLayout/vacancy.tsx",
      "parent": "/_homeLayout"
    },
    "/admin/_adminLayout": {
      "filePath": "admin/_adminLayout.tsx",
      "parent": "/admin",
      "children": [
        "/admin/_adminLayout/announcement",
        "/admin/_adminLayout/vacancy",
        "/admin/_adminLayout/"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/_homeLayout/": {
      "filePath": "_homeLayout/index.tsx",
      "parent": "/_homeLayout"
    },
    "/admin/_adminLayout/announcement": {
      "filePath": "admin/_adminLayout/announcement.tsx",
      "parent": "/admin/_adminLayout"
    },
    "/admin/_adminLayout/vacancy": {
      "filePath": "admin/_adminLayout/vacancy.tsx",
      "parent": "/admin/_adminLayout"
    },
    "/admin/_adminLayout/": {
      "filePath": "admin/_adminLayout/index.tsx",
      "parent": "/admin/_adminLayout"
    }
  }
}
ROUTE_MANIFEST_END */
