/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeLayoutImport } from './routes/_homeLayout'
import { Route as HomeLayoutIndexImport } from './routes/_homeLayout/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as HomeLayoutVacancyImport } from './routes/_homeLayout/vacancy'
import { Route as HomeLayoutStudyProgramProfileImport } from './routes/_homeLayout/studyProgramProfile'
import { Route as HomeLayoutStudentsAssociationInfoImport } from './routes/_homeLayout/studentsAssociationInfo'
import { Route as HomeLayoutAnnouncementImport } from './routes/_homeLayout/announcement'
import { Route as HomeLayoutAboutImport } from './routes/_homeLayout/about'

// Create/Update Routes

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_homeLayout',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutIndexRoute = HomeLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutVacancyRoute = HomeLayoutVacancyImport.update({
  id: '/vacancy',
  path: '/vacancy',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutStudyProgramProfileRoute =
  HomeLayoutStudyProgramProfileImport.update({
    id: '/studyProgramProfile',
    path: '/studyProgramProfile',
    getParentRoute: () => HomeLayoutRoute,
  } as any)

const HomeLayoutStudentsAssociationInfoRoute =
  HomeLayoutStudentsAssociationInfoImport.update({
    id: '/studentsAssociationInfo',
    path: '/studentsAssociationInfo',
    getParentRoute: () => HomeLayoutRoute,
  } as any)

const HomeLayoutAnnouncementRoute = HomeLayoutAnnouncementImport.update({
  id: '/announcement',
  path: '/announcement',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutAboutRoute = HomeLayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_homeLayout': {
      id: '/_homeLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_homeLayout/about': {
      id: '/_homeLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeLayoutAboutImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/announcement': {
      id: '/_homeLayout/announcement'
      path: '/announcement'
      fullPath: '/announcement'
      preLoaderRoute: typeof HomeLayoutAnnouncementImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/studentsAssociationInfo': {
      id: '/_homeLayout/studentsAssociationInfo'
      path: '/studentsAssociationInfo'
      fullPath: '/studentsAssociationInfo'
      preLoaderRoute: typeof HomeLayoutStudentsAssociationInfoImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/studyProgramProfile': {
      id: '/_homeLayout/studyProgramProfile'
      path: '/studyProgramProfile'
      fullPath: '/studyProgramProfile'
      preLoaderRoute: typeof HomeLayoutStudyProgramProfileImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/vacancy': {
      id: '/_homeLayout/vacancy'
      path: '/vacancy'
      fullPath: '/vacancy'
      preLoaderRoute: typeof HomeLayoutVacancyImport
      parentRoute: typeof HomeLayoutImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/_homeLayout/': {
      id: '/_homeLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutIndexImport
      parentRoute: typeof HomeLayoutImport
    }
  }
}

// Create and export the route tree

interface HomeLayoutRouteChildren {
  HomeLayoutAboutRoute: typeof HomeLayoutAboutRoute
  HomeLayoutAnnouncementRoute: typeof HomeLayoutAnnouncementRoute
  HomeLayoutStudentsAssociationInfoRoute: typeof HomeLayoutStudentsAssociationInfoRoute
  HomeLayoutStudyProgramProfileRoute: typeof HomeLayoutStudyProgramProfileRoute
  HomeLayoutVacancyRoute: typeof HomeLayoutVacancyRoute
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutAboutRoute: HomeLayoutAboutRoute,
  HomeLayoutAnnouncementRoute: HomeLayoutAnnouncementRoute,
  HomeLayoutStudentsAssociationInfoRoute:
    HomeLayoutStudentsAssociationInfoRoute,
  HomeLayoutStudyProgramProfileRoute: HomeLayoutStudyProgramProfileRoute,
  HomeLayoutVacancyRoute: HomeLayoutVacancyRoute,
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof HomeLayoutRouteWithChildren
  '/about': typeof HomeLayoutAboutRoute
  '/announcement': typeof HomeLayoutAnnouncementRoute
  '/studentsAssociationInfo': typeof HomeLayoutStudentsAssociationInfoRoute
  '/studyProgramProfile': typeof HomeLayoutStudyProgramProfileRoute
  '/vacancy': typeof HomeLayoutVacancyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof HomeLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof HomeLayoutAboutRoute
  '/announcement': typeof HomeLayoutAnnouncementRoute
  '/studentsAssociationInfo': typeof HomeLayoutStudentsAssociationInfoRoute
  '/studyProgramProfile': typeof HomeLayoutStudyProgramProfileRoute
  '/vacancy': typeof HomeLayoutVacancyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof HomeLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_homeLayout': typeof HomeLayoutRouteWithChildren
  '/_homeLayout/about': typeof HomeLayoutAboutRoute
  '/_homeLayout/announcement': typeof HomeLayoutAnnouncementRoute
  '/_homeLayout/studentsAssociationInfo': typeof HomeLayoutStudentsAssociationInfoRoute
  '/_homeLayout/studyProgramProfile': typeof HomeLayoutStudyProgramProfileRoute
  '/_homeLayout/vacancy': typeof HomeLayoutVacancyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_homeLayout/': typeof HomeLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/announcement'
    | '/studentsAssociationInfo'
    | '/studyProgramProfile'
    | '/vacancy'
    | '/auth/login'
    | '/auth/register'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/announcement'
    | '/studentsAssociationInfo'
    | '/studyProgramProfile'
    | '/vacancy'
    | '/auth/login'
    | '/auth/register'
    | '/'
  id:
    | '__root__'
    | '/_homeLayout'
    | '/_homeLayout/about'
    | '/_homeLayout/announcement'
    | '/_homeLayout/studentsAssociationInfo'
    | '/_homeLayout/studyProgramProfile'
    | '/_homeLayout/vacancy'
    | '/auth/login'
    | '/auth/register'
    | '/_homeLayout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_homeLayout",
        "/auth/login",
        "/auth/register"
      ]
    },
    "/_homeLayout": {
      "filePath": "_homeLayout.tsx",
      "children": [
        "/_homeLayout/about",
        "/_homeLayout/announcement",
        "/_homeLayout/studentsAssociationInfo",
        "/_homeLayout/studyProgramProfile",
        "/_homeLayout/vacancy",
        "/_homeLayout/"
      ]
    },
    "/_homeLayout/about": {
      "filePath": "_homeLayout/about.tsx",
      "parent": "/_homeLayout"
    },
    "/_homeLayout/announcement": {
      "filePath": "_homeLayout/announcement.tsx",
      "parent": "/_homeLayout"
    },
    "/_homeLayout/studentsAssociationInfo": {
      "filePath": "_homeLayout/studentsAssociationInfo.tsx",
      "parent": "/_homeLayout"
    },
    "/_homeLayout/studyProgramProfile": {
      "filePath": "_homeLayout/studyProgramProfile.tsx",
      "parent": "/_homeLayout"
    },
    "/_homeLayout/vacancy": {
      "filePath": "_homeLayout/vacancy.tsx",
      "parent": "/_homeLayout"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/_homeLayout/": {
      "filePath": "_homeLayout/index.tsx",
      "parent": "/_homeLayout"
    }
  }
}
ROUTE_MANIFEST_END */
